[package]
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
name = "lazyhtml-sys"
version = "0.1.0"

[[test]]
harness = false
name = "test"

[build-dependencies]
bindgen = "0.26.2"
glob = "0.2.11"

[dev-dependencies]
glob = "0.2.11"
serde = "1.0.9"
serde_derive = "1.0.9"
serde_json = "1.0.2"

[dev-dependencies.rustc-test]
features = ["capture"]
version = "0.2.0"
